kind: Service
apiVersion: v1
metadata:
  name: configserver
  labels:
    app: springactuator
spec:
  ports:
    - name: http
      nodePort: 30088
      port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    app: config-server
  type: NodePort