kind: Service
apiVersion: v1
metadata:
  name: catalog-iiif-content-search
  labels:
    app: springactuator
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8009
      targetPort: 8009
  selector:
    app: catalog-iiif-content-search
  type: ClusterIP