apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ../../../argo-apps/base/shared-apps.yaml
  - ../../../argo-apps/base/configserver.yaml
  - ../../../argo-apps/base/catalog-metadata-service.yaml
  - ../../../argo-apps/base/catalog-search-index-service.yaml
  - ../../../argo-apps/base/catalog-item-service.yaml
  - ../../../argo-apps/base/catalog-iiif-presentation-service.yaml
  - ../../../argo-apps/base/catalog-iiif-content-search-service.yaml
  - ../../../argo-apps/base/ingress.yaml