kind: Service
apiVersion: v1
metadata:
  name: catalog-search-index-service
  labels:
    app: springactuator
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8006
      targetPort: 8006
  selector:
    app: catalog-search-index-service
  type: ClusterIP
