kind: Service
apiVersion: v1
metadata:
  name: spring-boot-admin
  labels:
    app: springactuator
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8060
      targetPort: 8060
  selector:
    app: spring-boot-admin
  type: ClusterIP
