kind: Service
apiVersion: v1
metadata:
  name: catalog-iiif-presentation-service
  labels:
    app: springactuator
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8011
      targetPort: 8011
  selector:
    app: catalog-iiif-presentation-service
  type: ClusterIP
