kind: Service
apiVersion: v1
metadata:
  name: catalog-item-service
  labels:
    app: springactuator
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8004
      targetPort: 8004
  selector:
    app: catalog-item-service
  type: ClusterIP