kind: Service
apiVersion: v1
metadata:
  name: catalog-metadata-service
  labels:
    app: springactuator
spec:
  ports:
    - name: http
      port: 8019
      protocol: TCP
      targetPort: 8019
  selector:
    app: catalog-metadata-service
  type: ClusterIP
