apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nbno

resources:
  - catalog-metadata-service-ingress.yaml
  - catalog-item-service-ingress.yaml
  - catalog-iiif-presentation-service-ingress.yaml